---
title       : My first Slidify'ed slides
subtitle    : Slidify is cool
author      : Bertrand Rigaldies
job         : Data Nerd
framework   : html5slides        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

```{r required_libs, results = 'hide'}
require(rCharts)
```

## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

## Cars Distance vs. Speed Plot

```{r}
data(cars)
plot(cars$dist, cars$speed)
```

--- .class #id 

## Cars Data

```{r}
head(cars)
```

--- .class #id 

## Cars Speed Histogram

```{r}
hist(cars$speed)
```

--- .class #id 

## rChart 1

```{r echo = FALSE, results = 'asis'}
haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart', data = subset(haireye, Sex == 'Male'))
n1$save('n1.html')
cat('<iframe src="n1.html" width=100%, height=600></iframe>')
```

--- .class #id
